import crypto from "node:crypto";

// vendors.ssn_number is encrypted at rest (R-PII). Layout: AES-256-GCM with a
// random IV, stored base64(iv | authTag | ciphertext). Because random-IV
// ciphertext can't be unique-indexed, the UNIQUE constraint lives on the
// separate deterministic ssn_number_hash column (HMAC-SHA256 of the raw SSN)
// — also what equality lookups must query against.
//
// Key: SSN_ENCRYPTION_KEY — 64 hex chars (32 bytes), generated by the owner
// (`openssl rand -hex 32`). Rotating it requires re-encrypting stored values.

const IV_LENGTH = 12;
const TAG_LENGTH = 16;

function key(): Buffer {
  const hex = process.env.SSN_ENCRYPTION_KEY ?? "";
  if (!/^[0-9a-fA-F]{64}$/.test(hex)) {
    throw new Error(
      "SSN_ENCRYPTION_KEY must be 64 hex characters (openssl rand -hex 32).",
    );
  }
  return Buffer.from(hex, "hex");
}

export function encryptSsn(plain: string): string {
  const iv = crypto.randomBytes(IV_LENGTH);
  const cipher = crypto.createCipheriv("aes-256-gcm", key(), iv);
  const ciphertext = Buffer.concat([cipher.update(plain, "utf8"), cipher.final()]);
  return Buffer.concat([iv, cipher.getAuthTag(), ciphertext]).toString("base64");
}

export function decryptSsn(stored: string): string {
  const buf = Buffer.from(stored, "base64");
  const decipher = crypto.createDecipheriv(
    "aes-256-gcm",
    key(),
    buf.subarray(0, IV_LENGTH),
  );
  decipher.setAuthTag(buf.subarray(IV_LENGTH, IV_LENGTH + TAG_LENGTH));
  return Buffer.concat([
    decipher.update(buf.subarray(IV_LENGTH + TAG_LENGTH)),
    decipher.final(),
  ]).toString("utf8");
}

/** Deterministic digest for ssn_number_hash — the unique index + lookups. */
export function hashSsn(plain: string): string {
  return crypto.createHmac("sha256", key()).update(plain).digest("hex");
}
